global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/prometheus-xyzabc/metrics'
    static_configs:
      - targets: ['localhost:8000']

#  - job_name: "django"
#    static_configs:
#      - targets: [ "localhost:8000" ]
#  - job_name: postgres-exporter
#    static_configs:
#        - targets: ["postgres-exporter:9187"]
