# Generated by Django 5.0.3 on 2024-03-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_sample_delete_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.sample'),
        ),
    ]
