# Generated by Django 5.0.3 on 2024-03-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_document_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path_to_template', models.FileField(blank=True, upload_to='')),
                ('program_name', models.CharField(max_length=500)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_surname', models.CharField(max_length=200)),
                ('applicant_patronomic', models.CharField(max_length=200)),
                ('address_country', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=200)),
                ('address_street', models.CharField(max_length=200)),
                ('current_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
