# Generated by Django 5.0.3 on 2024-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_documentconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentconsent',
            name='address_building_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='address_house_flat_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='address_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='applicant_date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
