# Generated by Django 5.0.3 on 2024-03-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_documentconsent_address_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentconsent',
            name='application_number',
            field=models.IntegerField(null=True),
        ),
    ]
