# Generated by Django 5.0.3 on 2024-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_documentconsent_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path_to_template', models.FileField(blank=True, upload_to='')),
                ('program_name', models.CharField(max_length=500)),
                ('application_number', models.IntegerField(null=True)),
                ('main_applicant_name', models.CharField(max_length=200)),
                ('main_applicant_surname', models.CharField(max_length=200)),
                ('main_applicant_patronomic', models.CharField(max_length=200)),
                ('second_applicant_name', models.CharField(max_length=200)),
                ('second_applicant_surname', models.CharField(max_length=200)),
                ('second_applicant_patronomic', models.CharField(max_length=200)),
                ('second_applicant_date_of_birth', models.DateField(null=True)),
                ('address_index', models.IntegerField(null=True)),
                ('address_country', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=200)),
                ('address_street', models.CharField(max_length=200)),
                ('address_building_number', models.SmallIntegerField(null=True)),
                ('address_house_flat_number', models.SmallIntegerField(null=True)),
                ('current_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='path_to_template',
            field=models.FileField(blank=True, upload_to='upload_sample/'),
        ),
    ]
