# Generated by Django 5.0.3 on 2024-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_documentnotification_alter_sample_path_to_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='path_to_template',
            field=models.FileField(blank=True, upload_to='upload_sample/%Y-%m-%d/'),
        ),
    ]
