# Generated by Django 5.0.3 on 2024-04-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_sample_path_to_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample'),
        ),
    ]
