# Generated by Django 5.0.3 on 2024-05-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_document_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='passport_date_of_issue',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='passport_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='passport_place_giving',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='passport_seria',
            field=models.IntegerField(null=True),
        ),
    ]
