# Generated by Django 5.0.3 on 2024-05-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_alter_sample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentconsent',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample'),
        ),
    ]
