# Generated by Django 5.0.3 on 2024-05-06 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_documentconsent_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')])),
            ],
        ),
    ]
