# Generated by Django 5.0.3 on 2024-05-06 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_russianphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentconsent',
            name='applicant_phone_number',
            field=models.CharField(default='+79998887716', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')]),
        ),
    ]
