# Generated by Django 5.0.3 on 2024-05-16 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_documentconsent_applicant_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentnotification',
            old_name='address_building_number',
            new_name='applicant1_build_number',
        ),
        migrations.RenameField(
            model_name='documentnotification',
            old_name='address_house_flat_number',
            new_name='applicant1_flat_number',
        ),
        migrations.RenameField(
            model_name='documentnotification',
            old_name='address_index',
            new_name='applicant1_index',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='main_applicant_name',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='main_applicant_patronomic',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='main_applicant_surname',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='second_applicant_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='second_applicant_name',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='second_applicant_patronomic',
        ),
        migrations.RemoveField(
            model_name='documentnotification',
            name='second_applicant_surname',
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_patronomic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_percent_contribution',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_phone_number',
            field=models.CharField(default='+79998887716', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')]),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_snils',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_surname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant1_uni_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_build_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_flat_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_patronomic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_percent_contribution',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_phone_number',
            field=models.CharField(default='+79998887716', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')]),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_snils',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_surname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='applicant2_uni_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='fee',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='head_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='head_patronomic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='head_surname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='program_destiny',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample'),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='uni_department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='program_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
