# Generated by Django 5.0.3 on 2024-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_rename_address_building_number_documentnotification_applicant1_build_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnotification',
            name='program_usage',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
