# Generated by Django 5.0.3 on 2024-05-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_documentnotification_program_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuthorsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path_to_template', models.FileField(blank=True, upload_to='')),
                ('applicant1_name', models.CharField(blank=True, max_length=200)),
                ('applicant1_surname', models.CharField(blank=True, max_length=200)),
                ('applicant1_patronomic', models.CharField(blank=True, max_length=200)),
                ('applicant1_date_birth', models.DateField(null=True)),
                ('applicant1_passport_seria', models.IntegerField(null=True)),
                ('applicant1_passport_number', models.IntegerField(null=True)),
                ('applicant1_passport_date_of_issue', models.DateField(null=True)),
                ('applicant1_passport_place_giving', models.CharField(max_length=500, null=True)),
                ('applicant1_inn', models.CharField(blank=True, max_length=200)),
                ('applicant1_snils', models.CharField(blank=True, max_length=200)),
                ('applicant1_bank_info', models.CharField(blank=True, max_length=200)),
                ('applicant1_account_number', models.CharField(blank=True, max_length=200)),
                ('applicant1_bik', models.CharField(blank=True, max_length=200)),
                ('applicant1_bank_inn', models.CharField(blank=True, max_length=200)),
                ('applicant1_bank_kpp', models.CharField(blank=True, max_length=200)),
                ('applicant1_corr_account', models.CharField(blank=True, max_length=200)),
                ('applicant2_name', models.CharField(blank=True, max_length=200)),
                ('applicant2_surname', models.CharField(blank=True, max_length=200)),
                ('applicant2_patronomic', models.CharField(blank=True, max_length=200)),
                ('applicant2_date_birth', models.DateField(null=True)),
                ('applicant2_passport_seria', models.IntegerField(null=True)),
                ('applicant2_passport_number', models.IntegerField(null=True)),
                ('applicant2_passport_date_of_issue', models.DateField(null=True)),
                ('applicant2_passport_place_giving', models.CharField(max_length=500, null=True)),
                ('applicant2_inn', models.CharField(blank=True, max_length=200)),
                ('applicant2_snils', models.CharField(blank=True, max_length=200)),
                ('applicant2_bank_info', models.CharField(blank=True, max_length=200)),
                ('applicant2_account_number', models.CharField(blank=True, max_length=200)),
                ('applicant2_bik', models.CharField(blank=True, max_length=200)),
                ('applicant2_bank_inn', models.CharField(blank=True, max_length=200)),
                ('applicant2_bank_kpp', models.CharField(blank=True, max_length=200)),
                ('applicant2_corr_account', models.CharField(blank=True, max_length=200)),
                ('authors_award', models.SmallIntegerField(blank=True, null=True)),
                ('applicant1_authors_award', models.SmallIntegerField(blank=True, null=True)),
                ('applicant2_authors_award', models.SmallIntegerField(blank=True, null=True)),
                ('template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample')),
            ],
        ),
    ]
