# Generated by Django 5.0.3 on 2024-05-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_documentauthorsaward_program_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentauthorsaward',
            name='applicant1_authors_award',
        ),
        migrations.RemoveField(
            model_name='documentauthorsaward',
            name='applicant2_authors_award',
        ),
    ]
