# Generated by Django 5.0.3 on 2024-05-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_remove_documentauthorsaward_applicant1_authors_award_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDiplomaPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path_to_template', models.FileField(blank=True, upload_to='')),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('student_surname', models.CharField(blank=True, max_length=200)),
                ('student_patronomic', models.CharField(blank=True, max_length=200)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('org_surname', models.CharField(blank=True, max_length=200)),
                ('org_patronomic', models.CharField(blank=True, max_length=200)),
                ('practice_company', models.CharField(blank=True, max_length=200)),
                ('practice_address', models.CharField(blank=True, max_length=200)),
                ('practice_date_from', models.DateField(null=True)),
                ('practice_date_to', models.DateField(null=True)),
                ('agreement_number', models.CharField(blank=True, max_length=200)),
                ('date_agreement', models.DateField(null=True)),
                ('template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample')),
            ],
        ),
    ]
