# Generated by Django 5.0.3 on 2024-05-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_documentdiplomapractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSACB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path_to_template', models.FileField(blank=True, upload_to='')),
                ('project_sponsor', models.CharField(blank=True, max_length=200)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_developer', models.CharField(blank=True, max_length=200)),
                ('project_purpose', models.CharField(blank=True, max_length=200)),
                ('project_tasks', models.CharField(blank=True, max_length=500)),
                ('project_deadline', models.DateField(auto_now=True)),
                ('project_participants', models.CharField(blank=True, max_length=200)),
                ('project_short_description', models.CharField(blank=True, max_length=200)),
                ('projects_integration', models.CharField(blank=True, max_length=200)),
                ('expected_final_results', models.CharField(blank=True, max_length=200)),
                ('project_financing_sources', models.CharField(blank=True, max_length=200)),
                ('current_date', models.DateField(auto_now=True)),
                ('template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample')),
            ],
        ),
    ]
