# Generated by Django 5.0.3 on 2024-05-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_documentsacb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-created_at',), 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='path_to_template',
            field=models.FileField(blank=True, upload_to='upload_sample/%Y-%m-%d/', verbose_name='Путь до файла'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название шаблона'),
        ),
    ]
