# Generated by Django 5.0.3 on 2024-06-02 12:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_alter_sample_options_alter_sample_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documentauthorsaward',
            options={'verbose_name': 'Документ на авт.вознаграждение', 'verbose_name_plural': 'Документы на авт.вознаграждение'},
        ),
        migrations.AlterModelOptions(
            name='documentconsent',
            options={'verbose_name': 'Документ согласие на персональные данные', 'verbose_name_plural': 'Документы согласие на персональные данные'},
        ),
        migrations.AlterModelOptions(
            name='documentnotification',
            options={'verbose_name': 'Документ на уведомление', 'verbose_name_plural': 'Документы на уведомление'},
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_account_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер счета заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_bank_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Банк заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_bank_inn',
            field=models.CharField(blank=True, max_length=200, verbose_name='ИНН Банка заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_bank_kpp',
            field=models.CharField(blank=True, max_length=200, verbose_name='КПП Банка заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_bik',
            field=models.CharField(blank=True, max_length=200, verbose_name='БИК заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_corr_account',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кор. счет заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_date_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_inn',
            field=models.CharField(blank=True, max_length=200, verbose_name='ИНН заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_passport_date_of_issue',
            field=models.DateField(null=True, verbose_name='Дата выдачи паспорта заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_passport_number',
            field=models.IntegerField(null=True, verbose_name='Номер паспорта заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_passport_place_giving',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан паспорт заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_passport_seria',
            field=models.IntegerField(null=True, verbose_name='Серия паспорта заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_patronomic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_snils',
            field=models.CharField(blank=True, max_length=200, verbose_name='СНИЛС заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant1_surname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_account_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер счета заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_bank_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Банк заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_bank_inn',
            field=models.CharField(blank=True, max_length=200, verbose_name='ИНН Банка заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_bank_kpp',
            field=models.CharField(blank=True, max_length=200, verbose_name='КПП Банка заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_bik',
            field=models.CharField(blank=True, max_length=200, verbose_name='БИК заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_corr_account',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кор. счет заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_date_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_inn',
            field=models.CharField(blank=True, max_length=200, verbose_name='ИНН заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_passport_date_of_issue',
            field=models.DateField(null=True, verbose_name='Дата выдачи паспорта заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_passport_number',
            field=models.IntegerField(null=True, verbose_name='Номер паспорта заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_passport_place_giving',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан паспорт заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_passport_seria',
            field=models.IntegerField(null=True, verbose_name='Серия паспорта заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_patronomic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_snils',
            field=models.CharField(blank=True, max_length=200, verbose_name='СНИЛС заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='applicant2_surname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='authors_award',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Сумма вознаграждения'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='path_to_template',
            field=models.FileField(blank=True, upload_to='', verbose_name='Путь до шаблона'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='program_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample', verbose_name='Имя шаблона'),
        ),
        migrations.AlterField(
            model_name='documentauthorsaward',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='address_building_number',
            field=models.SmallIntegerField(null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='address_city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='address_country',
            field=models.CharField(max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='address_house_flat_number',
            field=models.SmallIntegerField(null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='address_index',
            field=models.IntegerField(null=True, verbose_name='Индекс здания'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='address_street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='applicant_date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='applicant_name',
            field=models.CharField(max_length=200, verbose_name='Имя заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='applicant_patronomic',
            field=models.CharField(max_length=200, verbose_name='Отчество заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='applicant_phone_number',
            field=models.CharField(default='+79998887716', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')], verbose_name='Номер телефона заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='applicant_surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='application_number',
            field=models.IntegerField(null=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='passport_date_of_issue',
            field=models.DateField(null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='passport_number',
            field=models.IntegerField(null=True, verbose_name='Номер паспорта заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='passport_place_giving',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='passport_seria',
            field=models.IntegerField(null=True, verbose_name='Серия паспорта заявителя'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='path_to_template',
            field=models.FileField(blank=True, upload_to='download_document/consent/%Y-%m-%d/', verbose_name='Путь до документа'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='program_name',
            field=models.CharField(max_length=500, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample', verbose_name='Имя шаблона'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_build_number',
            field=models.SmallIntegerField(null=True, verbose_name='Номер здания заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_flat_number',
            field=models.SmallIntegerField(null=True, verbose_name='Номер квартиры заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_index',
            field=models.IntegerField(null=True, verbose_name='Индекс здания заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_patronomic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_percent_contribution',
            field=models.SmallIntegerField(null=True, verbose_name='Процент вклада заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_phone_number',
            field=models.CharField(default='+79998887716', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')], verbose_name='Номер телефона заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_snils',
            field=models.CharField(blank=True, max_length=200, verbose_name='СНИЛС заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_surname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant1_uni_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность в университете заявителя 1'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_build_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер здания заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_flat_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер квартиры заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс здания заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_patronomic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_percent_contribution',
            field=models.SmallIntegerField(null=True, verbose_name='Процент вклада заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_phone_number',
            field=models.CharField(default='+79998887716', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79991234567'. Up to 11 digits allowed.", regex='^\\+?7?\\d{10,11}$')], verbose_name='Номер телефона заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_snils',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер квартиры заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_surname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='applicant2_uni_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность в университете заявителя 2'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='current_date',
            field=models.DateField(auto_now=True, verbose_name='Текущая дата'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='fee',
            field=models.SmallIntegerField(null=True, verbose_name='Пошлина в размере'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='head_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя руководителя'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='head_patronomic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество руководителя'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='head_surname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия руководителя'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='path_to_template',
            field=models.FileField(blank=True, upload_to='', verbose_name='Путь до шаблона'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='program_destiny',
            field=models.CharField(blank=True, max_length=500, verbose_name='Назначение программы'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='program_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='program_usage',
            field=models.CharField(blank=True, max_length=200, verbose_name='Где может быть использована программа'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample', verbose_name='Имя шаблона'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documentnotification',
            name='uni_department',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кафедра университета'),
        ),
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('document_authors_award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentauthorsaward')),
                ('document_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentconsent')),
                ('document_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentnotification')),
                ('template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample')),
            ],
        ),
    ]
