# Generated by Django 5.0.3 on 2024-06-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentconsent',
            options={'ordering': ('-created_at',), 'verbose_name': 'Документ согласие на персональные данные', 'verbose_name_plural': 'Документы согласие на персональные данные'},
        ),
        migrations.AlterModelOptions(
            name='documentnotification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Документ на уведомление', 'verbose_name_plural': 'Документы на уведомление'},
        ),
        migrations.AlterModelOptions(
            name='documentset',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пакет документов', 'verbose_name_plural': 'Пакеты документов'},
        ),
        migrations.AlterField(
            model_name='documentset',
            name='current_date',
            field=models.DateField(auto_now=True, verbose_name='Текущая дата'),
        ),
        migrations.AlterField(
            model_name='documentset',
            name='document_authors_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentauthorsaward', verbose_name='Документ на авторское вознаграждение'),
        ),
        migrations.AlterField(
            model_name='documentset',
            name='document_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentconsent', verbose_name='Документ об согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='documentset',
            name='document_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentnotification', verbose_name='Документ об согласии на уведомление об регистрации'),
        ),
        migrations.AlterField(
            model_name='documentset',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample', verbose_name='Имя шаблона'),
        ),
        migrations.AlterField(
            model_name='documentset',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название пакета'),
        ),
        migrations.CreateModel(
            name='ReviewProblemDocumentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_problem_document_consent_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Опишите вашу проблему с документом')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Идентификатор пользователя')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя')),
                ('review_text', models.TextField(blank=True, max_length=500)),
                ('document_consent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentconsent', verbose_name='Название документа')),
            ],
            options={
                'verbose_name': 'Отзыв об документе о соглашении',
                'verbose_name_plural': 'Отзывы об документе о соглашении',
            },
        ),
        migrations.CreateModel(
            name='ReviewProblemSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_problem_sample_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Опишите вашу проблему с шаблоном')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Идентификатор пользователя')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя')),
                ('review_text', models.TextField(blank=True, max_length=500)),
                ('sample_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sample', verbose_name='Название шаблона')),
            ],
            options={
                'verbose_name': 'Отзыв о шаблоне',
                'verbose_name_plural': 'Отзывы о шаблоне',
            },
        ),
    ]
