# Generated by Django 5.0.3 on 2024-06-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_alter_documentconsent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_head', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя руководителя')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='Отправлен', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reviewproblemdocumentconsent',
            name='review_problem_document_consent_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кратко опишите вашу проблему с документом'),
        ),
        migrations.AlterField(
            model_name='reviewproblemsample',
            name='review_problem_sample_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кратко опишите вашу проблему с шаблоном'),
        ),
        migrations.AlterField(
            model_name='reviewproblemsample',
            name='user_id',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='reviewproblemsample',
            name='user_name',
            field=models.CharField(blank=True, default='SAM', max_length=200, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='SignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.headofficer', verbose_name='Имя руководителя')),
                ('document_consent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentconsent', verbose_name='Название документа')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.status', verbose_name='Статус документа')),
            ],
        ),
    ]
