# Generated by Django 5.0.3 on 2024-06-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0026_headofficer_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headofficer',
            options={'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
        migrations.AlterModelOptions(
            name='signdocument',
            options={'verbose_name': 'Документ на подписание', 'verbose_name_plural': 'Документы на подписание'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='signdocument',
            name='FIO_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.headofficer', verbose_name='ФИО руководителя'),
        ),
    ]
